// Runtime catalog loaders. Prefecture index + per-prefecture city
// silhouettes + bboxes are served as static JSON from /public/data
// (generated by scripts/build-cities.mjs). The loaders fetch on
// demand so the view component can request the prefecture the user
// picked instead of bundling 12 MB of polygons.

export type Prefecture = {
  code: string; // 2-digit JIS code, '01'..'47'
  name: string; // 北海道, 東京都, etc.
  reading: string; // HOKKAIDO, TOKYO, etc.
};

export type CityBounds = {
  north: number;
  south: number;
  east: number;
  west: number;
};

export type City = {
  id: string; // 5-digit 市区町村コード
  name: string; // 下関市, 千代田区, 軽井沢町, etc.
  reading: string;
  path: string; // SVG path string on a 0-200 viewBox
  bounds: CityBounds;
};

export async function loadPrefectures(): Promise<Prefecture[]> {
  const res = await fetch('/data/prefectures.json');
  if (!res.ok) throw new Error(`Failed to load prefectures (${res.status})`);
  return (await res.json()) as Prefecture[];
}

export async function loadCities(prefCode: string): Promise<City[]> {
  const res = await fetch(`/data/cities/${prefCode}.json`);
  if (!res.ok) throw new Error(`Failed to load cities for prefecture ${prefCode} (${res.status})`);
  return (await res.json()) as City[];
}
