// Runtime catalog loaders. Prefecture index + per-prefecture city
// silhouettes + bboxes are served as static JSON from /public/data
// (generated by scripts/build-cities.mjs). The loaders fetch on
// demand so the view component can request the prefecture the user
// picked instead of bundling 12 MB of polygons.

export type Prefecture = {
  code: string; // 2-digit JIS code, '01'..'47'
  name: string; // 北海道, 東京都, etc.
  reading: string; // HOKKAIDO, TOKYO, etc.
};

export type CityBounds = {
  north: number;
  south: number;
  east: number;
  west: number;
};

export type City = {
  id: string; // 5-digit 市区町村コード
  name: string; // 下関市, 千代田区, 軽井沢町, etc.
  reading: string;
  // Default (level 1, standard) silhouette: main land mass + close-or-
  // sizeable adjacent islands. Always present.
  path: string; // SVG path string on a 0-200 viewBox
  bounds: CityBounds;
  // Optional level-0 (全島) variant — emitted only when the build pipeline
  // dropped one or more remote islands from the standard view. Falls back
  // to `path` / `bounds` when absent (i.e., the city has no remote islands
  // worth distinguishing).
  pathFull?: string;
  boundsFull?: CityBounds;
  // Optional level-2 (本島のみ) variant — emitted only when the city has a
  // dominant main polygon AND non-trivial near-island pieces that level 2
  // would strip. Absent when level 2 would render identically to level 1
  // (single-island cities, archipelago-guarded cities like 小笠原村).
  pathMain?: string;
  boundsMain?: CityBounds;
  // Optional: official hiragana for this code (e.g., "しものせきし").
  // Missing for the 北方領土 villages and a few historical merges where
  // localgovjp has no entry. The city picker's search / 50音 tabs treat
  // these as unmatched-on-kana but still searchable by name / reading.
  kana?: string;
  // Optional: Hokkaido 振興局 (subprefecture) id — populated only for
  // prefCode === '01'. See scripts/hokkaido-subregion.mjs.
  subregion?: string;
};

// Three discrete user-facing silhouette modes:
//   0 = 全島表示 — include every offshore island
//   1 = 標準     — drop tiny remote islands (default)
//   2 = 本島のみ  — single largest land mass only (falls back to 1 for
//                  archipelago-type cities where no main exists)
export type IslandLevel = 0 | 1 | 2;

export function resolveSilhouette(city: City, level: IslandLevel): { path: string; bounds: CityBounds } {
  if (level === 0 && city.pathFull && city.boundsFull) {
    return { path: city.pathFull, bounds: city.boundsFull };
  }
  if (level === 2 && city.pathMain && city.boundsMain) {
    return { path: city.pathMain, bounds: city.boundsMain };
  }
  return { path: city.path, bounds: city.bounds };
}

export async function loadPrefectures(): Promise<Prefecture[]> {
  const res = await fetch('/data/prefectures.json');
  if (!res.ok) throw new Error(`Failed to load prefectures (${res.status})`);
  return (await res.json()) as Prefecture[];
}

export async function loadCities(prefCode: string): Promise<City[]> {
  const res = await fetch(`/data/cities/${prefCode}.json`);
  if (!res.ok) throw new Error(`Failed to load cities for prefecture ${prefCode} (${res.status})`);
  return (await res.json()) as City[];
}

// Flat index of every municipality's bbox, used by the top page so a
// client-side GPS hit can match a municipality without fetching every
// prefecture's full polygon JSON.
export type BoundsEntry = CityBounds & {
  code: string;
  prefCode: string;
  name: string;
};

export async function loadBounds(): Promise<BoundsEntry[]> {
  const res = await fetch('/data/bounds.json');
  if (!res.ok) throw new Error(`Failed to load bounds index (${res.status})`);
  return (await res.json()) as BoundsEntry[];
}

// Pick the municipality whose bbox contains (lat, lng). Multiple bboxes
// can match (e.g., a 政令市 parent overlaps; islands; nested coastlines)
// — break ties by the smallest bbox area so a user in 横浜市西区 maps to
// 横浜市 rather than to 神奈川県全体. Returns null if no bbox contains
// the point.
export function findMunicipality(
  coords: { lat: number; lng: number },
  bounds: BoundsEntry[],
): BoundsEntry | null {
  const { lat, lng } = coords;
  let best: BoundsEntry | null = null;
  let bestArea = Infinity;
  for (const b of bounds) {
    if (lat < b.south || lat > b.north || lng < b.west || lng > b.east) continue;
    const area = (b.north - b.south) * (b.east - b.west);
    if (area < bestArea) {
      best = b;
      bestArea = area;
    }
  }
  return best;
}
