// Runtime catalog loaders. Prefecture index + per-prefecture city
// silhouettes + bboxes are served as static JSON from /public/data
// (generated by scripts/build-cities.mjs). The loaders fetch on
// demand so the view component can request the prefecture the user
// picked instead of bundling 12 MB of polygons.

export type Prefecture = {
  code: string; // 2-digit JIS code, '01'..'47'
  name: string; // 北海道, 東京都, etc.
  reading: string; // HOKKAIDO, TOKYO, etc.
};

export type CityBounds = {
  north: number;
  south: number;
  east: number;
  west: number;
};

export type City = {
  id: string; // 5-digit 市区町村コード
  name: string; // 下関市, 千代田区, 軽井沢町, etc.
  reading: string;
  path: string; // SVG path string on a 0-200 viewBox
  bounds: CityBounds;
  // Optional: official hiragana for this code (e.g., "しものせきし").
  // Missing for the 北方領土 villages and a few historical merges where
  // localgovjp has no entry. The city picker's search / 50音 tabs treat
  // these as unmatched-on-kana but still searchable by name / reading.
  kana?: string;
  // Optional: Hokkaido 振興局 (subprefecture) id — populated only for
  // prefCode === '01'. See scripts/hokkaido-subregion.mjs.
  subregion?: string;
};

export async function loadPrefectures(): Promise<Prefecture[]> {
  const res = await fetch('/data/prefectures.json');
  if (!res.ok) throw new Error(`Failed to load prefectures (${res.status})`);
  return (await res.json()) as Prefecture[];
}

export async function loadCities(prefCode: string): Promise<City[]> {
  const res = await fetch(`/data/cities/${prefCode}.json`);
  if (!res.ok) throw new Error(`Failed to load cities for prefecture ${prefCode} (${res.status})`);
  return (await res.json()) as City[];
}

// Flat index of every municipality's bbox, used by the top page so a
// client-side GPS hit can match a municipality without fetching every
// prefecture's full polygon JSON.
export type BoundsEntry = CityBounds & {
  code: string;
  prefCode: string;
  name: string;
};

export async function loadBounds(): Promise<BoundsEntry[]> {
  const res = await fetch('/data/bounds.json');
  if (!res.ok) throw new Error(`Failed to load bounds index (${res.status})`);
  return (await res.json()) as BoundsEntry[];
}

// Pick the municipality whose bbox contains (lat, lng). Multiple bboxes
// can match (e.g., a 政令市 parent overlaps; islands; nested coastlines)
// — break ties by the smallest bbox area so a user in 横浜市西区 maps to
// 横浜市 rather than to 神奈川県全体. Returns null if no bbox contains
// the point.
export function findMunicipality(
  coords: { lat: number; lng: number },
  bounds: BoundsEntry[],
): BoundsEntry | null {
  const { lat, lng } = coords;
  let best: BoundsEntry | null = null;
  let bestArea = Infinity;
  for (const b of bounds) {
    if (lat < b.south || lat > b.north || lng < b.west || lng > b.east) continue;
    const area = (b.north - b.south) * (b.east - b.west);
    if (area < bestArea) {
      best = b;
      bestArea = area;
    }
  }
  return best;
}
